/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_googlecode_android_scripting_Exec */

#ifndef _Included_com_googlecode_android_scripting_Exec
#define _Included_com_googlecode_android_scripting_Exec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_googlecode_android_scripting_Exec
 * Method:    createSubprocess
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_googlecode_android_1scripting_Exec_createSubprocess
  (JNIEnv *, jclass, jstring, jobjectArray, jobjectArray, jstring, jintArray);

/*
 * Class:     com_googlecode_android_scripting_Exec
 * Method:    setPtyWindowSize
 * Signature: (Ljava/io/FileDescriptor;IIII)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_android_1scripting_Exec_setPtyWindowSize
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     com_googlecode_android_scripting_Exec
 * Method:    waitFor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_android_1scripting_Exec_waitFor
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
