#
# These flags represent the build-time configuration of openssl for
# android
#
# They were pruned from the "Makefile" generated by running
# "./Configure linux-generic32 no-idea no-bf no-cast no-seed no-md2 -DL_ENDIAN zlib"
# in the openssl distribution directory
#

# From CLFAG=	
LOCAL_CFLAGS += -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DL_ENDIAN #-DTERMIO

# From DEPFLAG=
LOCAL_CFLAGS += -DOPENSSL_NO_BF -DOPENSSL_NO_CAMELLIA -DOPENSSL_NO_CAPIENG -DOPENSSL_NO_CAST -DOPENSSL_NO_CMS -DOPENSSL_NO_GMP -DOPENSSL_NO_IDEA -DOPENSSL_NO_JPAKE -DOPENSSL_NO_MD2 -DOPENSSL_NO_MDC2 -DOPENSSL_NO_RC5 -DOPENSSL_NO_RFC3779 -DOPENSSL_NO_SEED 

# Extra
LOCAL_CFLAGS += -DOPENSSL_NO_HW -DOPENSSL_NO_ENGINE -DOPENSSL_NO_EC -DOPENSSL_NO_ECDH -DOPENSSL_NO_ECDSA 

# Although we initially considered enabling ZLIB b/2361399
# this was disabled because some some sites fail to handshake if its enabled b/2710492 b/2710497
# LOCAL_CFLAGS += -DZLIB
